# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release

on:
  workflow_run:
    workflows: [ "Test" ]
    branches: [ main ]
    types:
      - completed
  create:
    tags:
      - "v*.*.*"
jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ "3.8", "3.11", "3.12" ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies [Linux]
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel cibuildwheel
          pip install -r requirements.txt
          pip install -r requirements-tests.txt
          pip install .
      - name: Tests
        run: |
          cd tests
          python -m unittest discover -p '*_tests.py' -v
      - name: Build package with Python ${{ matrix.python-version }}
        run: python -m build
      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/*
  publish:
    needs: build  # 确保 build 任务完成后再发布
    runs-on: ubuntu-latest
    steps:
      - name: Download all built wheels
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  release:
    needs: publish
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false



